認証周りの画面遷移を実装
yuji96/twitter-clone pull request #13
Opened 2020-08-24 11:56 UTC by yuji96

2020-08-25 02:28 UTC, kpppn requested changes
確認ください

2020-08-25 02:28 UTC, kpppn commented on tweets/views.py
> +class TimelineView(LoginRequiredMixin, generic.ListView):
`LoginRequiredMixin` つけるの`TweetCreate`クラスと間違えてる？

2020-08-25 02:39 UTC, yuji96 commented on tweets/views.py
> +class TimelineView(LoginRequiredMixin, generic.ListView):
TweetCreateにはつけ忘れていました。

タイムラインも非ユーザーには見えないようにしようと思ったのですが、一般的なサービスは鍵アカウントでなければ見えるので外します。

2020-08-31 09:34 UTC, kpppn approved these changes
lgtm

2020-08-31 09:34 UTC, merged